# Generated by Django 3.2 on 2021-04-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderMeal',
            new_name='OrderModel',
        ),
    ]
